#ifndef NETOS_PROTOCOLS_PROTOCOLS_H
#define NETOS_PROTOCOLS_PROTOCOLS_H

#define NETOS_IP_PROTOCOL_ICMP 1
#define NETOS_IP_PROTOCOL_IPV4_ENCAP 4
#define NETOS_IP_PROTOCOL_TCP 6
#define NETOS_IP_PROTOCOL_UDP 17
#define NETOS_IP_PROTOCOL_IPV6_ENCAP 41
#define NETOS_IP_PROTOCOL_GRE 47
#define NETOS_IP_PROTOCOL_ESP 50
#define NETOS_IP_PROTOCOL_AH 51
#define NETOS_IP_PROTOCOL_ICMPV6 58

#endif
