#ifndef PGEN_CMD_STRINGS_H
#define PGEN_CMD_STRINGS_H

#define ETH_ENABLE_CMD      "eth.enable"
#define ARP_ENABLE_CMD      "arp.enable"
#define ETH_DA_CMD          "eth.da"
#define ETH_SA_CMD          "eth.sa"
#define ETH_ETHERTYPE_CMD   "eth.ethertype"
#define VLAN_ID_CMD         "vlan.id"
#define VLAN_PRIORITY_CMD   "vlan.priority"
#define VLAN_NEXT_ETHER_CMD "vlan.next_ether"
#define ARP_OP_CMD          "arp.op"
#define ARP_SHA_CMD         "arp.sha"
#define ARP_SPA_CMD         "arp.spa"
#define ARP_THA_CMD         "arp.tha"
#define ARP_TPA_CMD         "arp.tpa"
#define IPV4_ENABLE_CMD     "ipv4.enable"
#define IPV4_VERSION_CMD    "ipv4.version"
#define IPV4_SRC_IP_CMD     "ipv4.src_ipaddr"
#define IPV4_DST_IP_CMD     "ipv4.dst_ipaddr"
#define IPV4_TTL_CMD        "ipv4.ttl"
#define IPV4_PROTOCOL_CMD   "ipv4.protocol"
#define IPV4_MF_CMD         "ipv4.mf"
#define IPV4_DF_CMD         "ipv4.df"
#define IPV4_CHKSUM_CMD     "ipv4.checksum"
#define ICMP_ENABLE_CMD     "icmp.enable"
#define ICMP_TYPE_CMD       "icmp.type"
#define ICMP_CODE_CMD       "icmp.code"
#define ICMP_CHECKSUM_CMD   "icmp.checksum"
#define ICMP_ID_CMD         "icmp.echo_req_id"
#define ICMP_SEQ_CMD        "icmp.echo_req_seq_no"
#define IPG_CMD             "ipg"
#define N_FRAMES_CMD        "n_frames"
#define LEN_CMD             "len"
#define IFNAME_CMD          "ifname"
#define RUN_CMD             "run"
#define EXIT_CMD            "exit"
#define QUIT_CMD            "quit"
#define HELP_CMD            "help"
#define ETH_ENABLE_STR      "Enables the Ethernet frame generation"
#define ARP_ENABLE_STR      "Enables the ARP frame generation"
#define ETH_DA_STR          "Set the Eth DA"
#define ETH_SA_STR          "Set the Eth SA"
#define ETH_ETHERTYPE_STR   "Set the Eth Ethertype"
#define VLAN_ID_STR         "Set the VLAN Id"
#define VLAN_PRIORITY_STR   "Set the VLAN priority"
#define VLAN_NEXT_ETHER_STR "Set the VLAN next ethertype"
#define ARP_OP_STR          "Set the ARP operation<request = 1/ reply = 2>"
#define ARP_SHA_STR         "Set the ARP's sender HW Addr"
#define ARP_SPA_STR         "Set the ARP sender Ip address"
#define ARP_THA_STR         "Set the ARP's target HW Address"
#define ARP_TPA_STR         "Set the ARP's target protocol address"
#define IPV4_VERSION_STR    "Set the IPv4 version"
#define IPV4_ENABLE_STR     "Enables the IPv4 frame generation"
#define IPV4_SRC_IP_STR     "Set the ipv4.src_ipaddr"
#define IPV4_DST_IP_STR     "Set the ipv4.dst_ipaddr"
#define IPV4_TTL_STR        "Set the IPv4 TTL"
#define IPV4_PROTOCOL_STR   "Set the IPV4 Protocol"
#define IPV4_MF_STR         "Set ipv4.more_fragments"
#define IPV4_DF_STR         "Set ipv4.dont_fragment"
#define IPV4_CHKSUM_STR     "Set the ipv4 checksum"
#define ICMP_ENABLE_STR     "Set the ICMP enable"
#define ICMP_TYPE_STR       "Set the ICMP type"
#define ICMP_CODE_STR       "Set the ICMP code"
#define ICMP_CHECKSUM_STR   "Set the ICMP checksum"
#define ICMP_ID_STR         "Set the ICMP Echo Request identifier"
#define ICMP_SEQ_STR        "Set the ICMP Echo Request sequence number"
#define IPG_STR             "Set the Inter packet gap (in nanoseconds)"
#define N_FRAMES_STR        "Set Number of frames to send"
#define LEN_STR             "Set the packet length"
#define IFNAME_STR          "Set the interface name"
#define RUN_STR             "Run the packet generator"
#define EXIT_STR            "Exit the packet generator"
#define QUIT_STR            EXIT_STR
#define HELP_STR            "Show help"
#define SEPARATOR_CMD       "==============="
#define SEPARATOR_STR       "=========================================="

#endif

