name: C cmake CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install System Packages
      run: |
        sudo apt update
        sudo apt install -y liblzma-dev libicu-dev
    - name: Compile
      run: |
        mkdir build; cd build; cmake .. -DCOMPILER_GCC=on -DDEBUG=on; make -j; mkdir dist/; cp -r netos_pgen netosd dist/;
        tag_name=`git tag | head -1`
        tar -zcf "netos_release_${tag_name}.tar.gz" -C dist .
    - name: Upload build artifact to Github Actions
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ github.ref_name }}
        path: netos_release*.tar.gz
        retention-days: 7
